import { createTheme } from '@material-ui/core/styles';

const theme = createTheme({
  typography: {
    useNextVariants: true,
    fontFamily: [
      'proxima-nova',
      'futura-pt',
      '"Helvetica Neue"',
      'Arial',
      'sans-serif',
      '"Apple Color Emoji"',
      '"Segoe UI Emoji"',
      '"Segoe UI Symbol"',
    ].join(','),
    htmlFontSize: 16,
    h1: {
      fontFamily: [
        'futura-pt',
        '"Helvetica Neue"',
        'Arial',
        'sans-serif',
      ].join(','),
      fontWeight: 700,
      fontSize: "6rem",
      lineHeight: "8rem",
      letterSpacing: "0.02em",
    }, 
    h2: {
      fontFamily: [
        'futura-pt',
        '"Helvetica Neue"',
        'Arial',
        'sans-serif',
      ].join(','),
      fontWeight: 700,
      fontSize: "5.333rem",
      lineHeight: "6.667rem",
      letterSpacing: "0.02em",
    },  
    h3: {
      fontFamily: [
        'futura-pt',
        '"Helvetica Neue"',
        'Arial',
        'sans-serif',
      ].join(','),
      fontWeight: 600,
      fontSize: "4.667rem",
      lineHeight: "6rem",
      letterSpacing: 0,
    }, 
    h4: {
      fontFamily: [
        'futura-pt',
        '"Helvetica Neue"',
        'Arial',
        'sans-serif',
      ].join(','),
      fontWeight: 600,
      fontSize: "4rem",
      lineHeight: "5.333rem",
      letterSpacing: "0.02em",
      textTransform: 'uppercase',
    },
    h5: {
      fontFamily: [
        'proxima-nova',
        '"Helvetica Neue"',
        'Arial',
        'sans-serif',
      ].join(','),
      fontWeight: 600,
      fontSize: "2.667rem",
      lineHeight: "4.667rem",
      letterSpacing: 0,
    },
    h6: {
      fontFamily: [
        'proxima-nova',
        '"Helvetica Neue"',
        'Arial',
        'sans-serif',
      ].join(','),
      fontWeight: 300,
      fontSize: "1rem",
      lineHeight: "1.333rem",
      letterSpacing: "0.08em",
      textTransform: 'uppercase',
    },
    subtitle1: {
      fontFamily: [
        'proxima-nova',
        '"Helvetica Neue"',
        'Arial',
        'sans-serif',
      ].join(','),
      fontWeight: 400,
      fontSize: "1.667rem",
      lineHeight: "2.333rem",
      letterSpacing: 0,
    },
    subtitle2: {
      fontFamily: [
        'proxima-nova',
        '"Helvetica Neue"',
        'Arial',
        'sans-serif',
      ].join(','),
      fontWeight: 600,
      fontSize: "1.667rem",
      lineHeight: "2.333rem",
      letterSpacing: "0.02em",
      textTransform: 'uppercase',
    },
    body1: {
      fontFamily: [
        'proxima-nova',
        '"Helvetica Neue"',
        'Arial',
        'sans-serif',
      ].join(','),
      fontWeight: 400,
      fontSize: "1.333rem",
      lineHeight: "2rem",
      letterSpacing: 0,
    },
    body2: {
      fontFamily: [
        'proxima-nova',
        '"Helvetica Neue"',
        'Arial',
        'sans-serif',
      ].join(','),
      fontWeight: 400,
      fontSize: "1rem",
      lineHeight: "1.333rem",
      letterSpacing: 0,
    },
    button: {
      fontFamily: [
        'proxima-nova',
        '"Helvetica Neue"',
        'Arial',
        'sans-serif',
      ].join(','),
      fontWeight: 300,
      fontSize: "1.167rem",
      lineHeight: "1.167rem",
      letterSpacing: "0.08em",
      textTransform: 'uppercase',
    },
  },
  palette: {
    common: {
      black: '#02222D',
      white: '#FDFFFF',
    },
    primary: {
      light: '#EFF6F9',
      main: '#0BC4FF',
      dark: '#033140',
      contrastText: '#EFF6F9',
    },
    secondary: {
      light: '#C7F6F3',
      main: '#0B7BFF',
      dark: '#0B7BFF',
      contrastText: '#000',
    },
    openTitle: '#02222D',
    customColorBlue: '#0bc4ff',
    customColorDarkBlue: '#022537',
    background: {
      default: '#FCFEFF',
    },
    error: {
      light: '#F05816',
      main: '#F05816',
      dark: '#F05816',
      contrastText: '#FDFFFF',
    },
    warning: {
      light: '#F0DA16',
      main: '#F0DA16',
      dark: '#F0DA16',
      contrastText: '#FDFFFF',
    },
    sucess: {
      light: '#16F0AE',
      main: '#16F0AE',
      dark: '#16F0AE',
      contrastText: '#FDFFFF',
    },
    info: {
      light: '#0B7BFF',
      main: '#0B7BFF',
      dark: '#0B7BFF',
      contrastText: '#FDFFFF',
    },
    grey: {
      50: '#FCFEFF',
      100: '#F7FDFF',
      200: '#EAF5F9',
      300: '#CADADE',
      400: '#ABBDC2',
      500: '#8DA1A6',
      600: '#71848A',
      700: '#57696E',
      800: '#3E4D52',
      900: '#273235',
    },
  },
  breakpoints: {
    keys: ["xs", "sm", "md", "lg", "xl"],
    values: {
      xs: 0,
      sm: 600,
      md: 960,
      lg: 1280,
      xl: 1920,
    },
  },
});

export default theme;
